import React from 'react';
import Link from 'next/link';

export const metadata = {
  title: 'Terms of Service • TSC AI',
  description: 'Terms of Service for TSC (The Student Companion) AI School OS.',
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-black text-neutral-100 py-16 px-4 sm:px-6 lg:px-8 max-w-4xl mx-auto">
      <div className="mb-8">
        <Link
          href="/"
          className="text-xs text-neutral-400 hover:text-white transition-colors"
        >
          ← Back to TSC
        </Link>
        <h1 className="text-3xl font-bold mt-4 text-white">Terms of Service</h1>
        <p className="text-xs text-neutral-400 mt-1">Last Updated: September 14, 2026</p>
      </div>

      <div className="space-y-6 text-sm text-neutral-300 leading-relaxed bg-[#111111] p-6 sm:p-8 rounded-2xl border border-white/10">
        <section className="space-y-2">
          <h2 className="text-base font-semibold text-white">1. Acceptance of Terms</h2>
          <p>
            By accessing or using TSC (&quot;The Student Companion&quot;), including our web application and associated WhatsApp and Telegram bots, you agree to comply with these Terms of Service.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold text-white">2. Purpose & Permitted Use</h2>
          <p>
            TSC is intended solely for educational, academic organization, and study assistance purposes. Users agree not to misuse the service or send malicious, offensive, or unlawful content.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold text-white">3. AI-Generated Output</h2>
          <p>
            Study advice, solutions, and summaries generated by the AI assistant are designed to support learning. Students are encouraged to verify important formulas and official curriculum guidelines independently.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold text-white">4. Modifications & Termination</h2>
          <p>
            We reserve the right to modify or terminate features of the service at any time. Users can delete or unlink their accounts via Settings.
          </p>
        </section>
      </div>
    </main>
  );
}
